analysisReport <- function()
{
  
  if(!exists("myData", envir=.GlobalEnv)){
    
    gmessage("You should load the data and create a model first.", title="Error", icon="error")
    return()
    
  }
  
  if(!exists("rankingsVars", envir=.GlobalEnv)){
    
    gmessage("You should create a model first.", title="Error", icon="error")
    return()
    
  }
    
  w5 <- gwindow(title="ClimMob - Create report", visible=FALSE, parent=c(0,0)) 
  group1 <- ggroup(horizontal=FALSE, spacing= 10, container=w5)
  
  ttitle <- glabel("Create report", container=group1)
  font(ttitle) <- list(size=16)
  
  glabel(paste("Items given:\n", 
               paste(itemsgivenVars, collapse=", "),"\nRanking variables:\n", 
               paste(rankingsVars, collapse=", "),
               "\nExplanatory variables:\n",
               paste(explanatoryVars, collapse=", "),
               "\nQuestion (aspect evaluated) variable:\n",
               paste(questionVar, collapse=", ")), container=group1)
  
  glabel("Select folder to write to:", container=group1)
  a1 <- gfilebrowse(text="Select folder to write to:", type="selectdir", container=group1)
  svalue(a1) <- getwd()
  group2 <- ggroup(horizontal=TRUE, spacing=10, container=group1, expand=TRUE)
  glabel("File name", container=group2)
  setfilename <- gtext(text=".doc", container=group2, width=2, height=1)
  size(setfilename) <- c(250,20)
  addHandlerChanged(setfilename, handler=function(h,...) {.GlobalEnv$filenameReport <- svalue(h$obj)})
  
  group3 <- ggroup(horizontal=TRUE, spacing=10, container=group1, expand=TRUE)
  addSpring(group3)
  b <- gbutton("Create report", container=group3, handler = function(h, ...){
   
    setwd(svalue(a1))
    
    rtf <- RTF(filenameReport, font.size=12)
    addPng(rtf, system.file("external/Try3-logo.png", package="Try3"), width=3.9, height=1.5)
    addNewLine(rtf)
    addHeader(rtf, title="Try3 report")
    addParagraph(rtf, paste("Author:", Sys.info()[["user"]]))
    addNewLine(rtf)
    addNewLine(rtf)
    addParagraph(rtf, "About Try3")
    addNewLine(rtf)
    addParagraph(rtf, "This is a report generated with Try3, an R package (plugin) to analyze data generated by observers who each compare three or more items from a larger set of items (Van Etten 2013). Try3 analyzes preference profiles from these data. It determines groups of observers with similar preference profiles, based on covariables. Triadic comparisons are thought to be a very reliable way to obtain data from observers (reference).\n\nTry3 was designed to compare different crop varieties and other agricultural climate change adaptation options in citizen science experiments with farmers (Van Etten 2011). The package was created as part of Bioversity International's research in the CGIAR Research Programme on Climate Change, Agriculture, and Food Security (CCAFS). However, the software could serve many other citizen science experiments.\n\nAlgorithms to do the analysis are from the psychotree package (reference). The user interface is built using gWidgets2 (Verzani 2013).\n")
    addNewLine(rtf)
    addNewLine(rtf)
    addParagraph(rtf, "Data and results")
    addNewLine(rtf)
    #No. of observers
    #No. of unique items
    #Table of unique items
    #Number of missing items
    n <- length(models)
    
    addParagraph(rtf, "Worth represents the relative score of each item. For each node identified, it sums to 1.")
    if(n>1){figures <- paste("s 1 to ", n, " show", sep="", collapse="")}else{figures <- " 1 shows"}
    addParagraph(rtf, paste("Figure", figures, " the worth values for each node.", collapse="", sep=""))
    
    nFigure <- 1
    nTable <- 1

    #models is a list of 1 or more bttree models
    addNewLine(rtf)
    for(i in 1:n)
    {
      
      table_i <- worth(models[[i]])
      Node <- rownames(table_i)
      table_i <- round(table_i, digits=3)
      table_i <- data.frame(Node, table_i)
      if(n>1) {question <- paste("for question", questions[i], collapse=" ")} else{question <-" "}
      addParagraph(rtf, paste("Table ", nFigure, ". Worth comparison ", question,"\n", collapse="", sep=""))  
      addTable(rtf, table_i, font.size=9, row.names=FALSE, NA.string="-")
      nTable <- nTable + 1
      addParagraph(rtf)
                   
    }
    
    addNewLine(rtf)
    addPageBreak(rtf)
    
    for(i in 1:n)
    {
      
      if(n>1) {question <- paste("for question", questions[i], collapse=" ")} else{question <-" "}
      addParagraph(rtf, paste("Figure ", nFigure, ". Graphical representation of model results ", question,"\n", collapse="", sep=""))  
      addPlot(rtf, plot.fun=plot, width=6, height=6, res=400, models[[i]])
      nFigure <- nFigure + 1
                   
    }
    
    addNewLine(rtf)
    addNewLine(rtf)
    addParagraph(rtf, "References\n")
    addParagraph(rtf, "Verzani, J.")  
    addParagraph(rtf, "van Etten, J. 2013. Try3: Analyze data generated by triadic comparisons. R package.") 
    addParagraph(rtf, "van Etten, J. 2011. Crowdsourcing crop improvement in sub-Saharan Africa: A proposal for a scalable and inclusive approach to food security. IDS Bulletin 42(4), 102-110.")
    addParagraph(rtf, "Martin, G.J. 2004. Ethnobotany. A Methods Manual. London: Earthscan.")
    done(rtf)
    
    dispose(w5)
    
    gmessage("Report created.", title="Done", icon="info")
    
  })
  
  visible(w5) <- TRUE
                 
}