.analysisReport <- function()
{
  
  la <- get("la")
  tl <- as.matrix(read.delim(system.file("external/MultilanguageAnalysisReport.txt", package="ClimMob"), header=FALSE))
  colnames(tl) <- NULL
    
  if(!exists("myData", envir=.GlobalEnv)){
    
    gmessage(tl[1,la], title="Error", icon="error")
    return()
    
  }
  
  if(!exists("rankingsVars", envir=.GlobalEnv)){
    
    gmessage(tl[2,la], title="Error", icon="error")
    return()
    
  }
  
  myData <- get("myData")
  observeridVar <- get("observeridVar")
  itemsgivenVars <- get("itemsgivenVars")
  rankingsVars <- get("rankingsVars")
  explanatoryVars <- get("explanatoryVars")
  questionVar <- get("questionVar")
  questionsAnalyzed <- get("questionsAnalyzed")
  models <- get("models")
  
  w5 <- gwindow(title=tl[3,la], visible=FALSE, parent=c(0,0)) 
  group1 <- ggroup(horizontal=FALSE, spacing= 10, container=w5)
  
  ttitle <- glabel(tl[4,la], container=group1)
  font(ttitle) <- list(size=16)
  
  g2 <- glabel(tl[5,la], container=group1)
  font(g2) <- list(size=12)
  a1 <- gfilebrowse(text=tl[6,la], type="selectdir", container=group1)
  svalue(a1) <- getwd()
  group2 <- ggroup(horizontal=TRUE, spacing=10, container=group1, expand=TRUE)
  g3 <- glabel(tl[7,la], container=group2)
  font(g3) <- list(size=12)
  setfilename <- gtext(text=".doc", container=group2, width=2, height=1)
  size(setfilename) <- c(250,20)
  #addHandlerChanged(setfilename, handler=function(h,...) {assign(filenameReport, svalue(h$obj), env=.GlobalEnv)})
  
  group3 <- ggroup(horizontal=TRUE, spacing=10, container=group1, expand=TRUE)
  addSpring(group3)
  b <- gbutton(tl[8,la], container=group3, handler = function(h, ...){
   
    setwd(svalue(a1))
    n <- length(models)
    
    #filenameReport <- get("filenameReport")
    
    rtf <- RTF(svalue(setfilename), font.size=12)
    addPng(rtf, system.file("external/ClimMob-logo.png", package="ClimMob"), width=3.9, height=2.2)
    addNewLine(rtf)
    addHeader(rtf, title=tl[9,la])
    addParagraph(rtf, paste(tl[10,la], Sys.info()[["user"]], sep=""))
    addNewLine(rtf)
    addNewLine(rtf)
    addParagraph(rtf, tl[11,la])
    addNewLine(rtf)
    addParagraph(rtf, tl[12,la])
    addNewLine(rtf)    
    addParagraph(rtf, tl[13,la])    
    addNewLine(rtf)
    addParagraph(rtf, tl[14,la])    
    addNewLine(rtf)
    addNewLine(rtf)
    addParagraph(rtf, tl[15,la])
    addNewLine(rtf)
    addText(rtf, paste(tl[16,la]," ", sep=""))
    addText(rtf, nrow(myData))
    addText(rtf, paste(" ", tl[17,la], " ", sep=""))
    addText(rtf, length(itemsgivenVars))
    addText(rtf, paste(" ", tl[18,la], " ", sep=""))
    uniqueItems <- unique(unlist(myData[itemsgivenVars]))
    addText(rtf, length(uniqueItems))
    addText(rtf, paste(" ", tl[19,la], " ", sep=""))
    addTable(rtf, uniqueItems)
    
    lq <- length(models)
    
    if(lq > 1)
    {
      
      addText(rtf, paste(tl[20,la]," "))
      addText(rtf, lq)
      addText(rtf, paste(" ", tl[21,la], " ", sep=""))
      addTable(rtf, questionsAnalyzed)
      
    }
    addText(rtf, tl[22,la])
    addText(rtf, tl[23,la])
    addText(rtf, tl[24,la])

    addNewLine(rtf)
    addText(rtf, tl[25,la])
    if(n>1){figures <- paste("s 1 to ", n, " show", sep="", collapse="")}else{figures <- " 1 shows"}
    addParagraph(rtf, paste("Figure", figures, " the worth values for each node.", collapse="", sep=""))
    
    nFigure <- 1
    nTable <- 1

    #models is a list of 1 or more bttree models
    addNewLine(rtf)
    for(i in 1:n)
    {
      
      table_i <- worth(models[[i]])
      Node <- rownames(table_i)
      table_i <- round(table_i, digits=3)
      table_i <- data.frame(Node, table_i)
      if(n>1) {question <- paste("for question", questionsAnalyzed[i], collapse=" ")} else{question <-" "}
      addParagraph(rtf, paste("Table ", nFigure, ". Worth comparison ", question,"\n", collapse="", sep=""))  
      addTable(rtf, table_i, font.size=9, row.names=FALSE, NA.string="-")
      nTable <- nTable + 1
      addParagraph(rtf)
                   
    }
    
    addNewLine(rtf)
    addPageBreak(rtf)
    
    for(i in 1:n)
    {
      
      if(n>1) {question <- paste("for question", questionsAnalyzed[i], collapse=" ")} else{question <-" "}
      addParagraph(rtf, paste("Figure ", nFigure, ". Graphical representation of model results ", question,"\n", collapse="", sep=""))  
      addPlot(rtf, plot.fun=plot, width=6, height=6, res=400, models[[i]])
      nFigure <- nFigure + 1
                   
    }
    
    addNewLine(rtf)
    addNewLine(rtf)
    addParagraph(rtf, "References\n")
    addParagraph(rtf, "Verzani, J. gWidgets2. R package on GitHub")  
    addParagraph(rtf, "van Etten, J. 2013. Try3: Analyze data generated by triadic comparisons. R package.") 
    addParagraph(rtf, "van Etten, J. 2011. Crowdsourcing crop improvement in sub-Saharan Africa: A proposal for a scalable and inclusive approach to food security. IDS Bulletin 42(4), 102-110.")
    addParagraph(rtf, "Martin, G.J. 2004. Ethnobotany. A Methods Manual. London: Earthscan.")
    done(rtf)
    
    dispose(w5)
    
    gmessage("Report created.", title="Done", icon="info")
    
    dispose(w5)
    
  })
  
  font(b) <- list(size=12)
  
  visible(w5) <- TRUE
                 
}