analysisReport <- function()
{
  
  w5 <- gwindow(title="Try3 - Create report", visible=FALSE, parent=c(0,0)) 
  group1 <- ggroup(horizontal=FALSE, spacing= 10, container=w5)
  
  glabel(paste("Model summary \nRanking variables:\n", 
              rankingVars,
              "\nExplanatory variables:\n",
              explVars,
              "\nQuestion (aspect evaluated) variable:\n",
              questionVar
  ), container=group1)
  
  glabel("Select folder to write to:", container=group1)
  a1 <- gfilebrowse(text="Select folder to write to:", type="selectdir", container=group1)
  
  group2 <- ggroup(horizontal=TRUE, spacing=10, container=group1, expand=TRUE)
  glabel("File name", container=group2)
  setfilename <- gtext(text=".doc", container=group2, width=2, height=1)
  size(setfilename) <- c(250,20)
  addHandlerChanged(setfilename, handler=function(h,...) {.GlobalEnv$filenameReport <- svalue(h$obj)})
  
  group3 <- ggroup(horizontal=TRUE, spacing=10, container=group1, expand=TRUE)
  addSpring(group3)
  b <- gbutton("Create report", container=group3, handler = function(h, ...){
   
    setwd(svalue(a1))
    
    rtf <- RTF(filenameReport, font.size=12)
    addPng(rtf, system.file("external/Try3-logo.png", package="Try3"), width=3.9, height=1.5)
    addNewLine(rtf)
    addHeader(rtf, title="Try3 report")
    addNewLine(rtf)
    addParagraph(rtf, paste("Author: ", Sys.info()[["user"]]))
    addParagraph(rtf, "Introduction\n")
    addParagraph(rtf, "This is a report generated with Try3, a R package (plugin) to analyze data generated by observers who each compare three or more items from a larger set of items (Van Etten 2013). Try3 analyzes preference profiles from these data. It determines groups of observers with similar preference profiles, based on covariables. Triadic comparisons are thought to be a very reliable way to obtain data from observers (reference). Try3 was designed with the goal in mind to compare different crop varieties as climate change adaptation options as a citizen science experiment (Van Etten 2011). However, the software could serve many other citizen science experiments. Algorithms to do the analysis are from the psychotree package (reference). The user interface is built using gWidgets2 (Verzani 2013).\n")
    addNewLine(rtf)
    addParagraph(rtf, "Data and model\n")
    addParagraph(rtf, "References\n")
              
    done(rtf)
    
  })
  
  visible(w5) <- TRUE
               
}