##Function by Achim Zeileis (improving a first version written by Jacob van Etten)

.predict.bttree <- function(object, newdata = NULL,
                            type = c("worth", "rank", "node"), ...) {
  type <- match.arg(type)
  
  ## get nodes
  nodes <- predict(object$mob, newdata = newdata, type = "node", ...)
  if(type == "node") return(nodes)
  
  ## get worth
  w <- worth(object)
  w <- w[as.character(nodes), ]
  rownames(w) <- NULL
  if(type == "worth") return(w)
  
  ## get order
  o <- t(apply(-w, 1, rank))
  return(o)
}

analysisReport <- function()
{
  
  if(!exists("myData", envir=.GlobalEnv)){
    
    gmessage("You should load the data and create a model first.", title="Error", icon="error")
    return()
    
  }
  
  if(!exists("rankingsVars", envir=.GlobalEnv)){
    
    gmessage("You should create a model first.", title="Error", icon="error")
    return()
    
  }
    
  w5 <- gwindow(title="Try3 - Create report", visible=FALSE, parent=c(0,0)) 
  group1 <- ggroup(horizontal=FALSE, spacing= 10, container=w5)
  
  glabel(paste("Model summary \nRanking variables:\n", 
              rankingVars,
              "\nExplanatory variables:\n",
              explVars,
              "\nQuestion (aspect evaluated) variable:\n",
              questionVar
  ), container=group1)
  
  glabel("Select folder to write to:", container=group1)
  a1 <- gfilebrowse(text="Select folder to write to:", type="selectdir", container=group1)
  
  group2 <- ggroup(horizontal=TRUE, spacing=10, container=group1, expand=TRUE)
  glabel("File name", container=group2)
  setfilename <- gtext(text=".doc", container=group2, width=2, height=1)
  size(setfilename) <- c(250,20)
  addHandlerChanged(setfilename, handler=function(h,...) {.GlobalEnv$filenameReport <- svalue(h$obj)})
  
  group3 <- ggroup(horizontal=TRUE, spacing=10, container=group1, expand=TRUE)
  addSpring(group3)
  b <- gbutton("Create report", container=group3, handler = function(h, ...){
   
    setwd(svalue(a1))
    
    rtf <- RTF(filenameReport, font.size=12)
    addPng(rtf, system.file("external/Try3-logo.png", package="Try3"), width=3.9, height=1.5)
    addNewLine(rtf)
    addHeader(rtf, title="Try3 report")
    addNewLine(rtf)
    addParagraph(rtf, paste("Author: ", Sys.info()[["user"]]))

    addParagraph(rtf, "About Try3\n")
    addParagraph(rtf, "This is a report generated with Try3, a R package (plugin) to analyze data generated by observers who each compare three or more items from a larger set of items (Van Etten 2013). Try3 analyzes preference profiles from these data. It determines groups of observers with similar preference profiles, based on covariables. Triadic comparisons are thought to be a very reliable way to obtain data from observers (reference).\nTry3 was designed to compare different crop varieties and other agricultural climate change adaptation options in citizen science experiments with farmers (Van Etten 2011). The package was created as part of Bioversity International's research in the CGIAR Research Programme on Climate Change, Agriculture, and Food Security (CCAFS). However, the software could serve many other citizen science experiments.\nAlgorithms to do the analysis are from the psychotree package (reference). The user interface is built using gWidgets2 (Verzani 2013).\n")
    addNewLine(rtf)

    addParagraph(rtf, "Data and results\n")
    
    #No. of observers
    #No. of unique items
    #Table of unique items
    #Number of missing items
    addParagraph(rtf, "Worth represents the relative score of each item. For each node identified, it sums to 1.\n")
    n <- length(models)
    nFigure <- 1
    nTable <- 1

    #models is a list of 1 or more bttree models
    
    for(i in 1:n)
    {
      
      table_i <- worth(models[[i]])
      if(n>1) {question <- paste("for question", questions[i], collapse=" ")} else{question <-" "}
      addParagraph(rtf, paste("Figure ", nFigure, "Worth comparison ", question,"\n", collapse=" "))  
      addTable(rtf, table_i, font.size=9, row.names=FALSE, NA.string="-")
      nTable <- nTable + 1
                   
    }
    
    for(i in 1:n)
    {
      
      if(n>1) {question <- paste("for question", questions[i], collapse=" ")} else{question <-" "}
      addParagraph(rtf, paste("Figure ", nFigure, ". Graphical representation of model results ", question,"\n", collapse=" "))  
      addPlot(rtf, plot.fun=, width=6, height=6, res=400, models[[i]])
      nFigure <- nFigure + 1
                   
    }
    
    addNewLine(rtf)
    addParagraph(rtf, "References\n")
              
    done(rtf)
    
  })
  
  visible(w5) <- TRUE
               
}